site_name: DevOps
site_author: niqdev
repo_url: https://github.com/niqdev/devops
theme: readthedocs
google_analytics: ['UA-68888222-4', 'niqdev.github.io']

pages:
    - Home: index.md
    - Docker: docker.md
    - Ansible: ansible.md
    - Cassandra: cassandra.md
    - ZooKeeper: zookeeper.md
    - Kafka: kafka.md
    - Hadoop: hadoop.md
    - Papers: papers.md
    - Other: other.md
