site_name: Provision Tools
site_author: niqdev
repo_url: https://github.com/niqdev/provision-tools
theme: readthedocs
google_analytics: ['UA-68888222-4']

pages:
    - Home: index.md
    - Ansible: ansible.md
    - Hadoop and Spark: hadoop-spark.md
    - Cassandra: cassandra.md
    - Zookeeper: zookeeper.md
    - Kafka: kafka.md
    - Other: other.md
