version: '3'

services:
  zookeeper:
    container_name: devops-zookeeper
    build:
      context: ../zookeeper
      args:
        - VERSION=3.4.10
    ports:
      - 12181:2181
    networks:
      - devops_network
  kafka:
    container_name: devops-kafka
    build: .
    depends_on:
      - zookeeper
    ports:
      - 19092:9092
    networks:
      - devops_network
    environment:
      - ZOOKEEPER_HOSTS="zookeeper:2181"

networks:
  devops_network:
