version: '3'

services:
  zookeeper:
    container_name: devops-zookeeper
    image: niqdev/zookeeper:latest
    ports:
      - 12181:2181
    networks:
      - devops_network
  kafka:
    container_name: devops-kafka
    image: niqdev/kafka:latest
    ports:
      - 19092:9092
      - 18083:8083
    networks:
      - devops_network
    environment:
      - ZOOKEEPER_HOSTS="zookeeper:2181"

networks:
  devops_network:
